/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'base-key',
    path: '/base-key',
    component: 'layout.base$view.base-key',
    meta: {
      title: 'base-key',
      i18nKey: 'route.base-key',
      localIcon: 'menu',
      order: 11
    }
  },
  {
    name: 'boot',
    path: '/boot',
    component: 'layout.header$view.boot',
    meta: {
      title: 'boot',
      hideInMenu: true,
      i18nKey: 'route.boot'
    }
  },
  {
    name: 'connect',
    path: '/connect',
    component: 'layout.header$view.connect',
    meta: {
      title: 'connect',
      i18nKey: 'route.connect',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'light',
    path: '/light',
    component: 'layout.base$view.light',
    meta: {
      title: 'light',
      i18nKey: 'route.light',
      localIcon: 'light-change',
      hideInMenu: true,
      order: 41
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'super-key',
    path: '/super-key',
    component: 'layout.base$view.super-key',
    meta: {
      title: 'super-key',
      i18nKey: 'route.super-key',
      localIcon: 'key-code',
      order: 21
    }
  },
  {
    name: 'tst',
    path: '/tst',
    component: 'layout.base$view.tst',
    meta: {
      title: 'tst',
      hideInMenu: true,
      i18nKey: 'route.tst'
    }
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      hideInMenu: true
    }
  }
];
